name: Oldwick Community Players
favicon: null
layout_spectrum: 0.44559132284484804
typography_spectrum: 0.9787622364237905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.16115426970645785
  lightness: 0.7690066434442997
  saturation: 0.06370948092080653
  rhythmicContrast: 0.8207273676525801
purpose: []
